### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by b4ssey** [n8fr8/gilgamesh#34]
Hello Nathan, I've tried to run this program on my android studio but it doesn't work. I want to know if i can use another software if possible

**Comment by n8fr8** [comment]
This project hasn't been worked on in quite sometime. What is it that you are looking to make it do? I might be able to recommend some other projects.

**Comment by b4ssey** [comment]
I noticed too. I'm interested in its "mesh" ability and its using "Wi-Fi or Wi-Fi direct" as a medium of sending messages too in a Bluetooth chat

**Comment by b4ssey** [comment]
Is it viable Nathan, or only 1 of the above medium is possible to be implemented.

**Comment by b4ssey** [comment]
Hey Nathan, I've still not heard any suggestions from your end.

**Comment by n8fr8** [comment]
This is the library project we are currently working on: https://github.com/guardianproject/ayanda

Otherwise, I would check out Briar: https://briarproject.org/

**Comment by b4ssey** [comment]
Thank you so much Sir Nathan, I really appreciate this.
